#!/usr/bin/env python3
"""
Here is our SBOM Supply Chain Analysis Tool.
We will use it to analyze components for A03 Software Supply Chain Failures, such as
  - Necessity, Known vulnerabilities, Maintenance, Source trust
It includes a snapshot feature that supports snapshots for comparing versions over time.
"""

# Here we import all the standard libraries we need:
# json for reading files, os/sys for file system and exit, time for small delays.
import argparse
import os
import json, os, subprocess, sys, time, argparse, platform
from datetime import datetime, timezone
from typing import Dict, List, Optional

# On Windows, npm is a .cmd batch script rather than a real executable,
# so Python's subprocess cannot find it by the name "npm" alone.
# We detect the OS here and pick the right command name accordingly.
# shell=True is also needed on Windows for .cmd scripts to run correctly.
IS_WINDOWS = platform.system() == 'Windows'
NPM = 'npm.cmd' if IS_WINDOWS else 'npm'

# These are the file paths the tool reads from and writes to.
# sbom.json is generated by cyclonedx-npm and lists all packages.
# package.json tells us which packages were installed in the project.
SBOM_FILE    = 'sbom.json'
PACKAGE_FILE = 'package.json'
OUTPUT_FILE  = 'supply_chain_analysis.md'
SNAPSHOT_DIR = 'snapshots'

# Here we set up a cache so we don't call "npm view" for the same package twice, which saves a lot of time.
_pkg_cache: Dict = {}


# Here we define some helper functions for reading JSON files and calculating maintenance status based on dates.
def read_json(path: str) -> Dict:
    # Here we open a JSON file and return its contents as a Python dictionary.
    try:
        with open(path, encoding='utf-8') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: '{path}' not found.", file=sys.stderr); sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: bad JSON in {path}: {e}", file=sys.stderr); sys.exit(1)

def days_since(date_str: str) -> Optional[int]:
    # Here we take an ISO-8601 date string, like "2023-01-15T10:00:00Z"
    # It will return how many days have passed since that date.
    # To judge whether a package is actively maintained or stale.
    try:
        d = datetime.fromisoformat(date_str.replace('Z', '+00:00'))
        return (datetime.now(timezone.utc) - d).days
    except Exception:
        return None


# Data fetching, here we are running npm commands to get vulnerability and registry data
def get_vulnerabilities() -> Dict:
    # Here we run "npm audit --json" to get a list of all known vulnerabilities
    # npm audit checks every installed package against
    # the npm security advisory database and reports any known CVEs.
    try:
        r = subprocess.run(
            [NPM, 'audit', '--json'],
            capture_output=True, text=True, timeout=60, shell=IS_WINDOWS
        )
        raw = r.stdout or r.stderr
        data = json.loads(raw)
    except Exception as e:
        print(f"Warning: npm audit failed ({e})", file=sys.stderr)
        return {}

    # Here we are parsing the output of npm audit to build a dictionary of vulnerabilities.
    vulns: Dict[str, List[Dict]] = {}
    for name, details in data.get('vulnerabilities', {}).items():
        fix = details.get('fixAvailable', False)
        if isinstance(fix, dict):
            fix = True
        entries = [
            {
                'severity':      via.get('severity', details.get('severity', 'unknown')),
                'title':         via.get('title', ''),
                'url':           via.get('url', ''),
                'fix_available': fix,
            }
            for via in details.get('via', [])
            if isinstance(via, dict)
        ]
        if entries:
            vulns[name] = entries
    return vulns

# Here we are fetching package metadata from the npm registry using "npm view".
# This gives us information like when the package was last published and whether it has been marked as deprecated by its maintainer.
# We check the cache first so we only make one network call per package.
def get_metadata(name: str) -> Dict:
    if name in _pkg_cache:
        return _pkg_cache[name]
    try:
        r = subprocess.run(
            [NPM, 'view', name, '--json'],
            capture_output=True, text=True, timeout=15, shell=IS_WINDOWS
        )
        if r.returncode == 0 and r.stdout.strip():
            _pkg_cache[name] = json.loads(r.stdout)
            return _pkg_cache[name]
    except Exception:
        pass
    # Small delay so we don't hammer the npm registry with too many requests
    time.sleep(0.05)
    return {}


# Analysis, here we are evaluating each package against the A03 supply chain criteria

# We check for the the most dangerous severity first so the worst issues will appear at the top of the report. 
SEVERITY_ORDER = ['critical', 'high', 'moderate', 'low']

def max_severity(vulns: List[Dict]) -> str:
    found = {v['severity'] for v in vulns}
    for s in SEVERITY_ORDER:
        if s in found:
            return s
    return 'none'

# This is the main analysis function that loops through every component in the SBOM and assesses it against the four A03 criteria: 
# necessity, known vulnerabilities, maintenance, and source trust.
def analyze(sbom: Dict, pkg_json: Dict) -> List[Dict]:
    components  = sbom.get('components', [])

    # We collect the names of packages that have been installed, from package.json, so we can flag them as direct dependencies in the report. 
    direct_deps = set(pkg_json.get('dependencies', {}).keys()) | \
                  set(pkg_json.get('devDependencies', {}).keys())

    advisories  = get_vulnerabilities()
    results     = []

    print(f"Analysing {len(components)} components...")
    for i, comp in enumerate(components, 1):
        name, version = comp.get('name'), comp.get('version')
        if not name or not version:
            continue
        if i % 50 == 0:
            print(f"  {i}/{len(components)}...")

        # Here we are checking for known vulnerabilities by looking up the package name in the advisories dictionary we built from npm audit.
        # If the package has any known vulnerabilities, we flag it as "Vulnerable". 
        # The severity level of each vulnerability is also recorded.
        vulns   = advisories.get(name, [])
        max_sev = max_severity(vulns)

        # Here we are assessing maintenance status by looking at the package metadata from the npm registry.
        # We check the "modified" or "created" time to see how recently the package was updated. 
        # If it hasn't been updated in over a year, we flag it as "Stale". 
        # If it was updated within the last 6 months, we flag it as "Active". 
        # We also check if the package is marked as deprecated by its maintainer, which is a strong signal that it should not be used.
        meta     = get_metadata(name)
        modified = meta.get('time', {}).get('modified') or meta.get('time', {}).get('created')
        d        = days_since(modified) if modified else None
        if d is None:
            maint = 'Unknown'
        elif d > 365:
            maint = f'Stale ({d}d)'
        elif d > 180:
            maint = f'Moderate ({d}d)'
        else:
            maint = f'Active ({d}d)'
        if meta.get('deprecated'):
            maint += ' [DEPRECATED]'

        # Here we are checking the source trust of the package. 
        # We look at the package URL to see where it came from. 
        # If it comes from npm, we flag it as "Official npm".
        # We also scan package names for suspicious patterns to catch potential typosquatting attacks.
        purl  = comp.get('purl', '')
        trust = 'Official npm' if 'pkg:npm/' in purl else f'Unknown ({purl})'
        
        # Here we check for suspicious patterns in package name that may indicate typosquatting
        suspicious_patterns = ['fake', 'malicious', 'test-', 'example-', 'demo-', 'sample-', 'temp-', 'tmp-']
        name_lower = name.lower()
        if any(pattern in name_lower for pattern in suspicious_patterns):
            trust = f'SUSPICIOUS: {trust}'

        # Store all the data we gathered for this package so we can use it
        # Saving it as a snapshot.
        results.append({
            'name':    name,
            'version': version,
            'direct':  name in direct_deps,
            'vulns':   vulns,
            'max_sev': max_sev,
            'maint':   maint,
            'trust':   trust,
        })

    return results

# Snapshot management, saving and loading analysis results for comparison over time
def save_snapshot(results: List[Dict], label: str = '') -> str:
    # Here we save the current analysis results to a timestamped JSON file, in the snapshots/ folder. 
    # This lets us run the tool again later and compare the two runs to see what changed between versions of the project.
    os.makedirs(SNAPSHOT_DIR, exist_ok=True)
    ts   = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')
    name = f"{SNAPSHOT_DIR}/snapshot_{ts}{'_' + label.replace(' ','_') if label else ''}.json"
    with open(name, 'w', encoding='utf-8') as f:
        json.dump({'label': label or ts, 'results': results}, f, indent=2)
    print(f"Snapshot saved: {name}")
    return name

def load_snapshot(path: str) -> Dict:
    # Here we read a previously saved snapshot so we can compare it to the current analysis results.
    # This allows us to see how the supply chain risk has evolved over time as we make changes to our dependencies or as new vulnerabilities are discovered.
    try:
        with open(path, encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"Error loading snapshot: {e}", file=sys.stderr); sys.exit(1)

# Here we are comparing two snapshots to detect what changed between runs.
# We check for: new packages added, packages removed, packages whose vulnerability severity got worse or better, and version changes.
def compare(old: Dict, new_results: List[Dict], new_label: str) -> Dict:
    # We assign a numeric rank to each severity level so we can compare them.
    # Lower rank = more dangerous, so going from rank 3 to rank 0 means worse.
    # example, we have a package that was "low" severity (rank 3) in the old snapshot, but now it's "critical" (rank 0) in the new snapshot,
    # that means the severity got worse.
    rank    = {s: i for i, s in enumerate(['critical', 'high', 'moderate', 'low', 'none'])}
    old_map = {r['name']: r for r in old.get('results', [])}
    new_map = {r['name']: r for r in new_results}
    old_names, new_names = set(old_map), set(new_map)

    sev_up, sev_down, ver_changed = [], [], []
    for name in sorted(old_names & new_names):
        o, n = old_map[name], new_map[name]
        # Check if the installed version changed between snapshots
        if o['version'] != n['version']:
            ver_changed.append({'name': name, 'old': o['version'], 'new': n['version']})
        # Check if the severity got worse or better
        or_, nr_ = rank.get(o['max_sev'], 4), rank.get(n['max_sev'], 4)
        if nr_ < or_:
            sev_up.append({'name': name, 'old': o['max_sev'], 'new': n['max_sev']})
        elif nr_ > or_:
            sev_down.append({'name': name, 'old': o['max_sev'], 'new': n['max_sev']})

    return {
        'old_label':   old.get('label', '?'),
        'new_label':   new_label,
        'added':       [new_map[n] for n in sorted(new_names - old_names)],
        'removed':     [old_map[n] for n in sorted(old_names - new_names)],
        'sev_up':      sev_up,
        'sev_down':    sev_down,
        'ver_changed': ver_changed,
    }

# Here we are generating the Markdown report that summarizes our findings.
def T(s: str, n: int) -> str:
    # Helper to truncate long strings so table columns stay readable
    return s[:n] + '…' if len(s) > n else s

def report(results: List[Dict], diff: Optional[Dict] = None):
    # Sort the results by severity so the most critical issues appear at the top of the report.
    rank = {'critical': 0, 'high': 1, 'moderate': 2, 'low': 3, 'none': 4}
    rs   = sorted(results, key=lambda r: rank.get(r['max_sev'], 4))

    # Here we are calculating summary statistics, to see the overall risk profile.
    total   = len(results)
    direct  = sum(1 for r in results if r['direct'])
    vuln_ct = sum(1 for r in results if r['vulns'])
    crit    = sum(1 for r in results if r['max_sev'] == 'critical')
    high    = sum(1 for r in results if r['max_sev'] == 'high')
    depr    = sum(1 for r in results if 'DEPRECATED' in r['maint'])
    stale   = sum(1 for r in results if 'Stale' in r['maint'])

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("# Result of our Software Supply Chain Analysis, SBOM Report:\n\n")
        f.write(f"**Generated**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n\n")

        f.write("## Summary: \n\n")
        f.write("| Metric | Count |\n|--------|-------|\n")
        f.write(f"| Total components | {total} |\n")
        f.write(f"| Direct dependencies | {direct} |\n")
        f.write(f"| Transitive dependencies | {total - direct} |\n")
        f.write(f"| Vulnerable components | {vuln_ct} |\n")
        f.write(f"| Critical severity | {crit} |\n")
        f.write(f"| High severity | {high} |\n")
        f.write(f"| Deprecated packages | {depr} |\n")
        f.write(f"| Stale packages (>1 yr) | {stale} |\n")
        suspicious = sum(1 for r in results if 'SUSPICIOUS' in r['trust'])
        f.write(f"| Suspicious packages | {suspicious} |\n\n")

        # Version comparison section,only written when the compare was used.
        # This shows what changed between two scans.
        if diff:
            f.write(f"## Changes: {diff['old_label']} → {diff['new_label']}\n\n")
            if diff['added']:
                f.write("### Added\n\n| Package | Version | Severity |\n|---------|---------|----------|\n")
                for p in diff['added']:
                    f.write(f"| {p['name']} | {p['version']} | {p['max_sev']} |\n")
                f.write("\n")
            if diff['removed']:
                f.write("### Removed\n\n| Package | Version |\n|---------|--------|\n")
                for p in diff['removed']:
                    f.write(f"| {p['name']} | {p['version']} |\n")
                f.write("\n")
            if diff['sev_up']:
                f.write("### Severity Worsened\n\n| Package | Was | Now |\n|---------|-----|-----|\n")
                for p in diff['sev_up']:
                    f.write(f"| {p['name']} | {p['old']} | **{p['new']}** |\n")
                f.write("\n")
            if diff['sev_down']:
                f.write("### Severity Improved\n\n| Package | Was | Now |\n|---------|-----|-----|\n")
                for p in diff['sev_down']:
                    f.write(f"| {p['name']} | {p['old']} | {p['new']} |\n")
                f.write("\n")
            if diff['ver_changed']:
                f.write("### Version Changed\n\n| Package | Old | New |\n|---------|-----|-----|\n")
                for p in diff['ver_changed']:
                    f.write(f"| {p['name']} | {p['old']} | {p['new']} |\n")
                f.write("\n")
            if not any(diff[k] for k in ['added', 'removed', 'sev_up', 'sev_down', 'ver_changed']):
                f.write("No changes detected.\n\n")

        # Full component table, where every package in the SBOM was sorted by severity.
        # This covers all four A03 criteria.
        f.write("## All Components\n\n")
        f.write("| Component | Version | Severity | Type | Maintenance | Source |\n")
        f.write("|-----------|---------|----------|------|-------------|--------|\n")
        for r in rs:
            kind = 'Direct' if r['direct'] else 'Transitive'
            f.write(f"| {T(r['name'],28)} | {T(r['version'],12)} | {r['max_sev']} | {kind} | {T(r['maint'],25)} | {T(r['trust'],20)} |\n")
        f.write("\n")

       # Here we are generating a detailed section for vulnerable components, showing the specific vulnerabilities and their severity levels.
       # This allows the user to see exactly which CVEs are affecting dependencies.
        vuln_comps = [r for r in rs if r['vulns']]
        if vuln_comps:
            f.write("## Vulnerability Details\n\n")
            for r in vuln_comps:
                f.write(f"### {r['name']}@{r['version']}\n\n")
                f.write(f"- **Type**: {'Direct' if r['direct'] else 'Transitive'}\n")
                f.write(f"- **Maintenance**: {r['maint']}\n\n")
                for v in r['vulns']:
                    fix = 'Yes' if v['fix_available'] else 'No'
                    f.write(f"- **{v['severity'].upper()}**: {v['title']}\n")
                    if v['url']:
                        f.write(f"  - Advisory: {v['url']}\n")
                    f.write(f"  - Fix available: {fix}\n")
                f.write("\n")

        # Here we are generating a section for maintenance, highlighting any packages that are deprecated or stale.
        issues = [r for r in results if 'DEPRECATED' in r['maint'] or 'Stale' in r['maint']]
        if issues:
            f.write("## Maintenance Concerns\n\n")
            f.write("| Package | Version | Issue |\n|---------|---------|-------|\n")
            for r in issues:
                issue = 'Deprecated' if 'DEPRECATED' in r['maint'] else 'Stale'
                f.write(f"| {r['name']} | {r['version']} | {issue} |\n")
            f.write("\n")

        # Here we are generating a section for suspicious packages that may indicate typosquatting.
        suspicious_comps = [r for r in results if 'SUSPICIOUS' in r['trust']]
        if suspicious_comps:
            f.write("## Suspicious Packages (Potential Typosquatting)\n\n")
            f.write("| Package | Version | Source |\n|---------|---------|--------|\n")
            for r in suspicious_comps:
                f.write(f"| {r['name']} | {r['version']} | {r['trust']} |\n")
            f.write("\n")

        # Recommendations.
        f.write("## Recommendations\n\n")
        if crit or high:
            f.write("**Immediate**: Run `npm audit fix` (or `--force` for breaking changes).\n\n")
        if depr:
            f.write("**Deprecated packages**: Find and migrate to maintained alternatives.\n\n")
        f.write("**Ongoing**: Integrate `npm audit` into CI/CD and monitor with Dependabot or Snyk.\n\n")

    print(f"Report saved: {OUTPUT_FILE}")


# Here we have the main function that ties everything together. 
# It handles command-line arguments, runs the analysis, generates the report, and manages snapshots for comparison.

def main():
    p = argparse.ArgumentParser(description='SBOM Supply Chain Analysis Tool')
    p.add_argument('--compare', metavar='SNAPSHOT', help='Previous snapshot to diff against')
    p.add_argument('--label',   default='',          help='Label for this snapshot')
    p.add_argument('--list',    action='store_true',  help='List saved snapshots and exit')
    p.add_argument('--no-save', action='store_true',  help='Skip saving a snapshot')
    args = p.parse_args()

    # Here we have a command-line interface that allows the user to list existing snapshots, compare against a previous snapshot
    # and control whether to save a new snapshot after the analysis.
    if args.list:
        snaps = sorted(f for f in os.listdir(SNAPSHOT_DIR) if f.endswith('.json')) \
                if os.path.isdir(SNAPSHOT_DIR) else []
        print('\n'.join(snaps) if snaps else 'No snapshots found.')
        return

    print("Result of our Supply Chain Analysis\n")

    # Then we load the SBOM, that was generated by cyclonedx-npm and our package.json, 
    # along with the vulnerability data from npm audit, and run the analysis function to evaluate each component against the A03 criteria.
    sbom     = read_json(SBOM_FILE)
    pkg_json = read_json(PACKAGE_FILE)
    results  = analyze(sbom, pkg_json)

    # If --compare was given, then we load the old snapshot and build a diff
    label = args.label or datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    diff  = None
    if args.compare:
        old  = load_snapshot(args.compare)
        diff = compare(old, results, label)

    # Write the Markdown report, then save a snapshot for comparisons
    report(results, diff)

    if not args.no_save:
        save_snapshot(results, args.label)

    # Here we are printing a quick summary to the console so the user can see the overall risk profile without opening the full report.
    print(f"\nTotal: {len(results)}  |  "
          f"Vulnerable: {sum(1 for r in results if r['vulns'])}  |  "
          f"Critical: {sum(1 for r in results if r['max_sev']=='critical')}  |  "
          f"High: {sum(1 for r in results if r['max_sev']=='high')}")

if __name__ == '__main__':
    main()